// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protofiles/simple.proto

package protofiles

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{0}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

func (m *SayHelloRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SayHelloRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type SayHelloResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloResponse) Reset()         { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()    {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{1}
}

func (m *SayHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloResponse.Unmarshal(m, b)
}
func (m *SayHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloResponse.Marshal(b, m, deterministic)
}
func (m *SayHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloResponse.Merge(m, src)
}
func (m *SayHelloResponse) XXX_Size() int {
	return xxx_messageInfo_SayHelloResponse.Size(m)
}
func (m *SayHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloResponse proto.InternalMessageInfo

func (m *SayHelloResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type FibonaciRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonaciRequest) Reset()         { *m = FibonaciRequest{} }
func (m *FibonaciRequest) String() string { return proto.CompactTextString(m) }
func (*FibonaciRequest) ProtoMessage()    {}
func (*FibonaciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{2}
}

func (m *FibonaciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonaciRequest.Unmarshal(m, b)
}
func (m *FibonaciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonaciRequest.Marshal(b, m, deterministic)
}
func (m *FibonaciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonaciRequest.Merge(m, src)
}
func (m *FibonaciRequest) XXX_Size() int {
	return xxx_messageInfo_FibonaciRequest.Size(m)
}
func (m *FibonaciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonaciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibonaciRequest proto.InternalMessageInfo

func (m *FibonaciRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FibonaciResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonaciResponse) Reset()         { *m = FibonaciResponse{} }
func (m *FibonaciResponse) String() string { return proto.CompactTextString(m) }
func (*FibonaciResponse) ProtoMessage()    {}
func (*FibonaciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{3}
}

func (m *FibonaciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonaciResponse.Unmarshal(m, b)
}
func (m *FibonaciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonaciResponse.Marshal(b, m, deterministic)
}
func (m *FibonaciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonaciResponse.Merge(m, src)
}
func (m *FibonaciResponse) XXX_Size() int {
	return xxx_messageInfo_FibonaciResponse.Size(m)
}
func (m *FibonaciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonaciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FibonaciResponse proto.InternalMessageInfo

func (m *FibonaciResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AverageRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageRequest) Reset()         { *m = AverageRequest{} }
func (m *AverageRequest) String() string { return proto.CompactTextString(m) }
func (*AverageRequest) ProtoMessage()    {}
func (*AverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{4}
}

func (m *AverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageRequest.Unmarshal(m, b)
}
func (m *AverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageRequest.Marshal(b, m, deterministic)
}
func (m *AverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageRequest.Merge(m, src)
}
func (m *AverageRequest) XXX_Size() int {
	return xxx_messageInfo_AverageRequest.Size(m)
}
func (m *AverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AverageRequest proto.InternalMessageInfo

func (m *AverageRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AverageResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{5}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MaxRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxRequest) Reset()         { *m = MaxRequest{} }
func (m *MaxRequest) String() string { return proto.CompactTextString(m) }
func (*MaxRequest) ProtoMessage()    {}
func (*MaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{6}
}

func (m *MaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxRequest.Unmarshal(m, b)
}
func (m *MaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxRequest.Marshal(b, m, deterministic)
}
func (m *MaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxRequest.Merge(m, src)
}
func (m *MaxRequest) XXX_Size() int {
	return xxx_messageInfo_MaxRequest.Size(m)
}
func (m *MaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaxRequest proto.InternalMessageInfo

func (m *MaxRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MaxResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxResponse) Reset()         { *m = MaxResponse{} }
func (m *MaxResponse) String() string { return proto.CompactTextString(m) }
func (*MaxResponse) ProtoMessage()    {}
func (*MaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_266a9d6d68e82ed0, []int{7}
}

func (m *MaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxResponse.Unmarshal(m, b)
}
func (m *MaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxResponse.Marshal(b, m, deterministic)
}
func (m *MaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxResponse.Merge(m, src)
}
func (m *MaxResponse) XXX_Size() int {
	return xxx_messageInfo_MaxResponse.Size(m)
}
func (m *MaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxResponse proto.InternalMessageInfo

func (m *MaxResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "protofiles.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "protofiles.SayHelloResponse")
	proto.RegisterType((*FibonaciRequest)(nil), "protofiles.FibonaciRequest")
	proto.RegisterType((*FibonaciResponse)(nil), "protofiles.FibonaciResponse")
	proto.RegisterType((*AverageRequest)(nil), "protofiles.AverageRequest")
	proto.RegisterType((*AverageResponse)(nil), "protofiles.AverageResponse")
	proto.RegisterType((*MaxRequest)(nil), "protofiles.MaxRequest")
	proto.RegisterType((*MaxResponse)(nil), "protofiles.MaxResponse")
}

func init() { proto.RegisterFile("src/protofiles/simple.proto", fileDescriptor_266a9d6d68e82ed0) }

var fileDescriptor_266a9d6d68e82ed0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xe5, 0xfe, 0x6a, 0xff, 0x76, 0xb8, 0x14, 0x79, 0x51, 0x50, 0xda, 0x05, 0xaa, 0x40,
	0x6a, 0x59, 0xa4, 0x15, 0xec, 0xd8, 0x81, 0xb8, 0x49, 0xa8, 0x2c, 0x92, 0x1d, 0x3b, 0x27, 0x9a,
	0x22, 0x4b, 0xce, 0x05, 0x3b, 0xa9, 0xca, 0xe3, 0xf0, 0xa6, 0x08, 0xe3, 0xc4, 0x49, 0x88, 0xe8,
	0xce, 0x33, 0xe7, 0xf8, 0x1b, 0xeb, 0x8c, 0x61, 0xac, 0x64, 0xb8, 0x48, 0x65, 0x92, 0x25, 0x6b,
	0x2e, 0x50, 0x2d, 0x14, 0x8f, 0x52, 0x81, 0xae, 0xee, 0x50, 0xb0, 0xc2, 0xf4, 0x19, 0x86, 0x3e,
	0xfb, 0x78, 0x42, 0x21, 0x12, 0x0f, 0xdf, 0x73, 0x54, 0x19, 0x9d, 0xc0, 0x60, 0xcd, 0xa5, 0xca,
	0x5e, 0x58, 0x84, 0x27, 0xe4, 0x94, 0xcc, 0x06, 0x9e, 0x6d, 0x50, 0x07, 0xfa, 0x82, 0x19, 0xb1,
	0xa3, 0xc5, 0xb2, 0x9e, 0x5e, 0xc0, 0x91, 0x85, 0xa9, 0x34, 0x89, 0x15, 0xd2, 0x11, 0xf4, 0x24,
	0xaa, 0x5c, 0x64, 0x06, 0x65, 0xaa, 0xe9, 0x1c, 0x86, 0x0f, 0x3c, 0x48, 0x62, 0x16, 0xf2, 0x62,
	0xf0, 0x08, 0x7a, 0x71, 0x1e, 0x05, 0x28, 0xb5, 0xb5, 0xeb, 0x99, 0xea, 0x1b, 0x6b, 0xad, 0xad,
	0xd8, 0x6e, 0x89, 0x9d, 0xc1, 0xe1, 0xcd, 0x06, 0x25, 0x7b, 0xc3, 0x5d, 0xd4, 0x39, 0x0c, 0x4b,
	0x67, 0x2b, 0x94, 0x94, 0xd0, 0x33, 0x80, 0x15, 0xdb, 0xee, 0x02, 0x9e, 0xc3, 0x9e, 0x76, 0xfd,
	0xfd, 0xc2, 0xcb, 0xcf, 0x0e, 0x1c, 0xf8, 0x7a, 0x1d, 0x3e, 0xca, 0x0d, 0x0f, 0x91, 0xde, 0x43,
	0xbf, 0x88, 0x8d, 0x8e, 0x5d, 0xbb, 0x1c, 0xb7, 0xb1, 0x19, 0x67, 0xd2, 0x2e, 0x9a, 0x81, 0x8f,
	0xd0, 0x2f, 0x62, 0xaa, 0x63, 0x1a, 0x39, 0xd7, 0x31, 0xcd, 0x64, 0x97, 0x84, 0xde, 0xc1, 0x7f,
	0x93, 0x0c, 0x75, 0xaa, 0xd6, 0x7a, 0xb0, 0xce, 0xb8, 0x55, 0xfb, 0xa1, 0xcc, 0x08, 0xbd, 0x86,
	0x7f, 0x2b, 0xb6, 0xa5, 0xa3, 0xaa, 0xcb, 0xa6, 0xe8, 0x1c, 0xff, 0xea, 0x17, 0x37, 0x97, 0xe4,
	0x76, 0xff, 0xb5, 0xf2, 0x47, 0x83, 0x9e, 0x3e, 0x5f, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8d,
	0xb0, 0xd4, 0x77, 0xd5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	Fibonaci(ctx context.Context, in *FibonaciRequest, opts ...grpc.CallOption) (SimpleService_FibonaciClient, error)
	Average(ctx context.Context, opts ...grpc.CallOption) (SimpleService_AverageClient, error)
	Max(ctx context.Context, opts ...grpc.CallOption) (SimpleService_MaxClient, error)
}

type simpleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimpleServiceClient(cc *grpc.ClientConn) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

func (c *simpleServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/protofiles.SimpleService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleServiceClient) Fibonaci(ctx context.Context, in *FibonaciRequest, opts ...grpc.CallOption) (SimpleService_FibonaciClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimpleService_serviceDesc.Streams[0], "/protofiles.SimpleService/Fibonaci", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceFibonaciClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SimpleService_FibonaciClient interface {
	Recv() (*FibonaciResponse, error)
	grpc.ClientStream
}

type simpleServiceFibonaciClient struct {
	grpc.ClientStream
}

func (x *simpleServiceFibonaciClient) Recv() (*FibonaciResponse, error) {
	m := new(FibonaciResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleServiceClient) Average(ctx context.Context, opts ...grpc.CallOption) (SimpleService_AverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimpleService_serviceDesc.Streams[1], "/protofiles.SimpleService/Average", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceAverageClient{stream}
	return x, nil
}

type SimpleService_AverageClient interface {
	Send(*AverageRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type simpleServiceAverageClient struct {
	grpc.ClientStream
}

func (x *simpleServiceAverageClient) Send(m *AverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleServiceAverageClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleServiceClient) Max(ctx context.Context, opts ...grpc.CallOption) (SimpleService_MaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimpleService_serviceDesc.Streams[2], "/protofiles.SimpleService/Max", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceMaxClient{stream}
	return x, nil
}

type SimpleService_MaxClient interface {
	Send(*MaxRequest) error
	Recv() (*MaxResponse, error)
	grpc.ClientStream
}

type simpleServiceMaxClient struct {
	grpc.ClientStream
}

func (x *simpleServiceMaxClient) Send(m *MaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleServiceMaxClient) Recv() (*MaxResponse, error) {
	m := new(MaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleServiceServer is the server API for SimpleService service.
type SimpleServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	Fibonaci(*FibonaciRequest, SimpleService_FibonaciServer) error
	Average(SimpleService_AverageServer) error
	Max(SimpleService_MaxServer) error
}

// UnimplementedSimpleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleServiceServer struct {
}

func (*UnimplementedSimpleServiceServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedSimpleServiceServer) Fibonaci(req *FibonaciRequest, srv SimpleService_FibonaciServer) error {
	return status.Errorf(codes.Unimplemented, "method Fibonaci not implemented")
}
func (*UnimplementedSimpleServiceServer) Average(srv SimpleService_AverageServer) error {
	return status.Errorf(codes.Unimplemented, "method Average not implemented")
}
func (*UnimplementedSimpleServiceServer) Max(srv SimpleService_MaxServer) error {
	return status.Errorf(codes.Unimplemented, "method Max not implemented")
}

func RegisterSimpleServiceServer(s *grpc.Server, srv SimpleServiceServer) {
	s.RegisterService(&_SimpleService_serviceDesc, srv)
}

func _SimpleService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.SimpleService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleService_Fibonaci_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibonaciRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimpleServiceServer).Fibonaci(m, &simpleServiceFibonaciServer{stream})
}

type SimpleService_FibonaciServer interface {
	Send(*FibonaciResponse) error
	grpc.ServerStream
}

type simpleServiceFibonaciServer struct {
	grpc.ServerStream
}

func (x *simpleServiceFibonaciServer) Send(m *FibonaciResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SimpleService_Average_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleServiceServer).Average(&simpleServiceAverageServer{stream})
}

type SimpleService_AverageServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*AverageRequest, error)
	grpc.ServerStream
}

type simpleServiceAverageServer struct {
	grpc.ServerStream
}

func (x *simpleServiceAverageServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleServiceAverageServer) Recv() (*AverageRequest, error) {
	m := new(AverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SimpleService_Max_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleServiceServer).Max(&simpleServiceMaxServer{stream})
}

type SimpleService_MaxServer interface {
	Send(*MaxResponse) error
	Recv() (*MaxRequest, error)
	grpc.ServerStream
}

type simpleServiceMaxServer struct {
	grpc.ServerStream
}

func (x *simpleServiceMaxServer) Send(m *MaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleServiceMaxServer) Recv() (*MaxRequest, error) {
	m := new(MaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SimpleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SimpleService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fibonaci",
			Handler:       _SimpleService_Fibonaci_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Average",
			Handler:       _SimpleService_Average_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Max",
			Handler:       _SimpleService_Max_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/protofiles/simple.proto",
}
