// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protofiles/simple.proto

package protofiles

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("src/protofiles/simple.proto", fileDescriptor_266a9d6d68e82ed0) }

var fileDescriptor_266a9d6d68e82ed0 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x2f, 0xce, 0xcc, 0x2d, 0xc8,
	0x49, 0xd5, 0x03, 0x8b, 0x08, 0x71, 0x21, 0x24, 0x8c, 0xf8, 0xb9, 0x78, 0x83, 0xc1, 0x72, 0xc1,
	0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x4e, 0x3c, 0x51, 0x48, 0xd2, 0x49, 0x6c, 0x60, 0xb6, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xed, 0xd7, 0xb9, 0x50, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleServiceClient interface {
}

type simpleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimpleServiceClient(cc *grpc.ClientConn) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

// SimpleServiceServer is the server API for SimpleService service.
type SimpleServiceServer interface {
}

// UnimplementedSimpleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleServiceServer struct {
}

func RegisterSimpleServiceServer(s *grpc.Server, srv SimpleServiceServer) {
	s.RegisterService(&_SimpleService_serviceDesc, srv)
}

var _SimpleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "src/protofiles/simple.proto",
}
